### PR TITLE
[OPS-881] Update haskell.nix, update nix code to use the new haskell.nix API

### PR DESCRIPTION
**Pull request by zhenyavinogradov**
Now the project can be built with the newest `haskell.nix`. Some haskell dependencies have been bumped because I had to generate a new cabal plan

### CODE REVIEW

**Comment by zhenyavinogradov** [comment]
I only changed `nix/default.nix` and removed `nix/overlays.nix`, all the other changed files are autogenerated

**Comment by zhenyavinogradov** [comment]
It seems that the maintenance system for this repository is still kinda awkward:
1. cabal plan used for generating `pkgs.nix` is not commited, so when we want to use a newer `plan-to-nix` version we have to regenerate the cabal plan, which might change which haskell module versions are used
2. `lootbox` dependencies fetched by cabal lack `.cabal` files, so we have to run `cabal` twice for generating the cabal plan: first to fetch the repositories, then we run `hpack` to generate `.cabal` files for them, then we rerun `cabal` to actually generate the plan. And I actually don't see `lootbox` used anywhere in the code
3. generated `pkgs.nix` depends on the whole directory, so the package has to be rebuilt even if some ignored files change

**Comment by mkaito** [comment]
So am I reading this correctly, in that @Haskell-mouse will remove the lootbox dependency and then we should stick with this instead of Stack?

**Comment by zhenyavinogradov** [comment]
I don't know how certain he is about removing the dependency, it's better to ask him. But if he does, then there is no reason to use stack. Also, this pull request just updates haskell.nix and does not touch anything else, so everything works the same way it does now on master (making you run `cabal` twice when generating `pkgs.nix`)

**Comment by mkaito** [comment]
Lootbox is ours, so we can also just fix it.

**Comment by zhenyavinogradov** [comment]
`lootbox` is not really "broken", it's more about an incompatible development approach. It uses stack which generates `.cabal` files from `package.yaml` files when building the project, and the `.cabal` files are not commited into the repository

**Comment by mkaito** [comment]
Alright, could you ping me again when @Haskell-mouse does what he said he'd do, so I can go over it again?

**Comment by zhenyavinogradov** [comment]
We could merge this PR for now then, so he would have the latest version of haskell.nix

**Pull request merged**
